### ISSUE TITLE
Last Questions Regarding my Site.

### ISSUE THREAD

**Issue by dasi0075** [dasi0075/ecommerce-pattern-library#15]
hi @thomasjbradley
This morning I was working on my site and took notes of 7 questions I don't know how to answer:

1# Extra Button showing up in the bottom of my home page (lots of people mentioned that on the test)

2# Why does my hamburguer nav shows up fine in homepage but when I move to other pages I get a question mark?

3# PRODUCTS CARDS (I am still quite confused in how to set them up, I don't know what I am missing that cant get different products on the page). 

4# the 'quantity form' not showing up in my checkout page

5# Can't see my icons on the payment page (amazon, credit_card, Paypal and visa). they are in my code but don't see them in my page.

6# In Checkout page my footer is all messed up. Why? If I am using the same default layout as the other pages?

7# How to change my buttons names (for instance, If I want to do a call to action for my sales page, or checkout written on the basic button for my checkout page).

These are my questions for my last attempts to try to finish this site.
Thank you.

PS: I think also have these two things done already.

![Screen Shot 2020-04-14 at 4 14 37 PM](https://user-images.githubusercontent.com/43067752/79269849-12c93c80-7e6b-11ea-8de7-9df85d4d73f8.png)

**Comment by thomasjbradley** [comment]
1: https://github.com/dasi0075/ecommerce-pattern-library/blob/master/index.html#L24

2: https://github.com/dasi0075/ecommerce-pattern-library/blob/master/_patterns/header/nav.html#L13-L14
Missing the `/` at the start of both `src` paths.

3: https://github.com/dasi0075/ecommerce-pattern-library/blob/master/products.html#L9
```
{% pattern cards/cards data=product %}
```
Add `data=product`, then refer to this step to see the changes you need to make in your pattern:
https://learn-the-web.algonquindesign.ca/courses/web-dev-4/jekyll-generators/#step-1

4: https://github.com/dasi0075/ecommerce-pattern-library/blob/master/_patterns/forms/quantity.html#L11
Missing closing `</select>`

5: Possibly related to 4

6. Probably related to 4

7: https://learn-the-web.algonquindesign.ca/courses/web-dev-4/building-pages-with-patterns/#step-6

---

Jekyll generators & homepage can’t be marked yet because of 3.

**Comment by dasi0075** [comment]
Thank you I think I got most of them fixed!! Thanks for the help
